import { useEffect, useRef, useState, type ReactNode } from "react";
import { UploadCloud } from "lucide-react";
import type { ScenarioAuditResult } from "../../demo/derivation/auditScenarioClients";

type DemoContext = { demoRunId: string; prospectCompanyName: string; projectName: string; scenarioName: string; status: string; injectedAt: string };
type DemoEvidenceCounts = { reservations: number; messages: number; sellerReports: number; vapiLogs: number; whatsappFollowups: number; evidence: number };
export type DemoInjectionQuantities = { reservations: number; vapiLogs: number; sellerReports: number; messages: number; prospectCompanyName?: string; projectName?: string; scenarioName?: string };
type AuditStatus = "not-audited" | "audited" | "approved";
type Props = { demoContext: DemoContext | null; simulatedDataInjected: boolean; counts: DemoEvidenceCounts; hasActiveDemoSession: boolean; hasScenario: boolean; auditResult: ScenarioAuditResult | null; auditStatus: AuditStatus; approved: boolean; canApprove: boolean; canInject: boolean; onGenerate: (quantities: DemoInjectionQuantities) => void; onAudit: () => void; onRegenerateRejected: () => void; onApprove: () => void; onInject: () => void; resetToken?: number };
type Tone = "slate" | "green" | "amber" | "blue" | "violet" | "red";
const tones: Record<Tone, string> = { slate: "border-slate-200 bg-slate-100 text-slate-900", green: "border-emerald-200 bg-emerald-100 text-emerald-800", amber: "border-amber-200 bg-amber-100 text-amber-800", blue: "border-blue-200 bg-blue-100 text-blue-800", violet: "border-violet-200 bg-violet-100 text-violet-800", red: "border-red-200 bg-red-100 text-red-800" };
const defaults: DemoInjectionQuantities = { reservations: 20, vapiLogs: 20, sellerReports: 20, messages: 20 };
const categories = [{ label: "Gestión de Reservas", key: "reservations" as const }, { label: "Marta Voz / VAPI", key: "vapiLogs" as const }, { label: "Registro de Seguimiento Comercial", key: "sellerReports" as const }, { label: "Mensajes entre el Equipo", key: "messages" as const }];
function Badge({ children, tone = "slate" }: { children: ReactNode; tone?: Tone }) { return <span className={`inline-flex rounded-full border px-3 py-1 text-xs font-black ${tones[tone]}`}>{children}</span>; }
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="text-xs font-black uppercase tracking-[0.16em] text-slate-600">{label}</div><div className="mt-2 break-words text-base font-black text-slate-950">{value}</div></div>; }

export default function DemoCommandEvidencePanel({ demoContext, simulatedDataInjected, counts, hasActiveDemoSession, hasScenario, auditResult, auditStatus, approved, canApprove, canInject, onGenerate, onAudit, onRegenerateRejected, onApprove, onInject, resetToken = 0 }: Props) {
  const [quantities, setQuantities] = useState<DemoInjectionQuantities>(defaults);
  const [prospectCompanyName, setProspectCompanyName] = useState(""); const [projectName, setProjectName] = useState(""); const [scenarioName, setScenarioName] = useState("");
  const layerTwoRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => { setQuantities(defaults); setProspectCompanyName(""); setProjectName(""); setScenarioName(""); }, [resetToken]);
  const updateQuantity = (key: keyof DemoInjectionQuantities, raw: string) => setQuantities((current) => ({ ...current, [key]: Math.max(0, Number.parseInt(raw, 10) || 0) }));
  const issuesFor = (category: string) => auditResult?.issues.filter((item) => item.category === category) || [];
  const statusLabel = !hasScenario ? "Pendiente de generación" : auditStatus === "approved" ? "Datos aprobados" : auditStatus === "audited" ? auditResult?.critical || auditResult?.repairable ? "Auditoría con bloqueos" : "Auditoría aprobable" : "Escenario sin auditar";
  const statusTone: Tone = auditStatus === "approved" ? "green" : auditStatus === "audited" && !(auditResult?.critical || auditResult?.repairable) ? "blue" : auditStatus === "audited" ? "red" : "amber";
  const action = "rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-600"; const secondary = "rounded-2xl bg-slate-200 px-5 py-4 text-sm font-black text-slate-950 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400";
  const total = counts.reservations + counts.vapiLogs + counts.sellerReports + counts.messages;
  const canRegenerateRejected = Boolean(auditResult?.repairable);
  return <section className="min-w-0 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">
    <div className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between"><div><h3 className="text-3xl font-black text-slate-950">FASE 04 Centro de Mando y Evidencia de la Operación</h3><p className="mt-2 max-w-4xl text-base font-semibold leading-7 text-slate-700">Estación para preparar, auditar y cargar datos simulados locales antes de la lectura de Intelligence.</p></div><div className="flex flex-wrap gap-2"><Badge tone={simulatedDataInjected ? "green" : "amber"}>{simulatedDataInjected ? "Datos demo cargados" : "Preparación"}</Badge><Badge tone="violet">Datos simulados</Badge><Badge tone="amber">No persistido</Badge></div></div>
    <div className="mt-5 rounded-3xl border border-amber-100 bg-amber-50 p-5"><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">Capa 01 · Preparación y carga de datos simulados</div><h4 className="mt-2 text-xl font-black text-slate-950">Qué está ocurriendo</h4><p className="mt-1 text-sm font-semibold text-slate-700">Configure la Empresa Demo, genere el escenario local y audite sus relaciones reales antes de cargarlo.</p>
      <div className="mt-4 grid gap-3 md:grid-cols-3">{[["Empresa activa", prospectCompanyName, setProspectCompanyName, "Empresa Demo"], ["Proyecto", projectName, setProjectName, "Proyecto de Empresa Demo"], ["Descripción del escenario demo", scenarioName, setScenarioName, "Lanzamiento comercial de proyecto habitacional"]].map(([label, value, setValue, placeholder]: any) => <div key={label} className="rounded-2xl border border-slate-100 bg-white p-4"><label className="text-xs font-black uppercase tracking-[0.16em] text-slate-600">{label}</label><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-base font-black text-slate-950 outline-none" /></div>)}</div>
      <div className="mt-6"><h4 className="text-lg font-black text-slate-950">Cantidad deseada de datos a generar</h4><div className="mt-5 grid gap-3 md:grid-cols-4">{categories.map((category) => <div key={category.label} className="rounded-2xl border border-amber-100 bg-white p-4"><div className="text-sm font-black leading-5 text-slate-950">{category.label}</div><input type="number" min={0} value={quantities[category.key]} onChange={(event) => updateQuantity(category.key, event.target.value)} className="mt-3 w-full rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-base font-black text-slate-950 outline-none" /></div>)}</div></div>
      <div className="mt-5 rounded-2xl border border-amber-100 bg-white p-4 text-sm font-black leading-6 text-slate-800">Generar datos → Auditar calidad → Aprobar → Cargar Empresa Demo simulada</div>
      <div className="mt-5 flex flex-col gap-3 rounded-3xl border border-amber-100 bg-white p-5 xl:flex-row xl:items-center xl:justify-between"><p className="text-sm font-semibold leading-6 text-slate-700">Cuando la configuración esté lista, continúe con el flujo controlado de Capa 02.</p><button type="button" onClick={() => layerTwoRef.current?.scrollIntoView({ behavior: "smooth", block: "start" })} className={secondary}>Siguiente paso: Capa 02</button></div>
      <div ref={layerTwoRef} className="mt-5 scroll-mt-64 rounded-3xl border border-amber-100 bg-white p-5"><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><div className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">Capa 02 · Flujo controlado</div><h4 className="mt-2 text-xl font-black text-slate-950">Proceso de generación</h4><p className="mt-1 text-sm font-semibold leading-6 text-slate-700">El panel presenta el estado decidido por DemoPage; no aplica reglas ni reparaciones locales.</p></div><Badge tone={statusTone}>{statusLabel}</Badge></div><div className="mt-5 flex flex-wrap gap-3"><button disabled={!hasActiveDemoSession} onClick={() => onGenerate({ ...quantities, prospectCompanyName: prospectCompanyName.trim() || "Empresa Demo", projectName: projectName.trim() || "Proyecto de Empresa Demo", scenarioName: scenarioName.trim() || "Lanzamiento comercial de proyecto habitacional" })} className={action}>Generar datos simulados</button><button disabled={!hasScenario} onClick={onAudit} className={secondary}>Auditar calidad</button><button disabled={!canRegenerateRejected} onClick={onRegenerateRejected} className={secondary}>Regenerar rechazados</button><button disabled={!canApprove} onClick={onApprove} className={action}>Aprobar datos</button></div></div>
      <div className="mt-5 overflow-hidden rounded-3xl border border-amber-100 bg-white"><div className="overflow-x-auto"><div className="grid min-w-[980px] grid-cols-[1.2fr_0.9fr_0.9fr_0.8fr_0.9fr_1fr_1fr] bg-amber-100/70 text-left text-xs font-black uppercase tracking-[0.16em] text-slate-950"><div className="p-4">Aplicación</div><div className="p-4">Generados</div><div className="p-4">Revisados</div><div className="p-4">Válidos</div><div className="p-4">Defectuosos</div><div className="p-4">Estado</div><div className="p-4">Acción</div></div>{categories.map((category) => { const issues = issuesFor(category.label); const generated = counts[category.key]; const reviewed = auditResult ? generated : 0; const valid = Math.max(0, reviewed - issues.length); const blocked = issues.some((item) => item.severity === "critical" || item.severity === "repairable"); const repairable = issues.some((item) => item.severity === "repairable"); return <div key={category.label} className="grid min-w-[980px] grid-cols-[1.2fr_0.9fr_0.9fr_0.8fr_0.9fr_1fr_1fr] border-t border-amber-100 text-sm font-semibold text-slate-800"><div className="p-4 font-black text-slate-950">{category.label}</div><div className="p-4">{generated}</div><div className="p-4">{reviewed}</div><div className="p-4">{valid}</div><div className="p-4">{issues.length}</div><div className="p-4"><Badge tone={!auditResult ? "slate" : blocked ? "red" : "green"}>{!auditResult ? "Pendiente" : blocked ? "Requiere regeneración" : "Validado"}</Badge></div><div className="p-4"><button disabled={!repairable} onClick={onRegenerateRejected} className="rounded-2xl bg-slate-200 px-4 py-3 text-xs font-black text-slate-950 disabled:cursor-not-allowed disabled:bg-slate-100 disabled:text-slate-400">Regenerar rechazados</button></div></div>; })}</div></div>
      {auditResult && <div className="mt-5 rounded-3xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap gap-2"><Badge tone="blue">Revisados: {auditResult.reviewed}</Badge><Badge tone="green">Válidos: {auditResult.valid}</Badge><Badge tone={auditResult.critical || auditResult.repairable ? "red" : "green"}>Bloqueantes: {auditResult.critical + auditResult.repairable}</Badge><Badge tone="amber">Warnings: {auditResult.warnings}</Badge></div><h5 className="mt-4 text-base font-black text-slate-950">Issues de auditoría real</h5>{auditResult.issues.length === 0 ? <p className="mt-2 text-sm font-semibold text-emerald-800">No se detectaron issues bloqueantes en el escenario vigente.</p> : <ul className="mt-3 space-y-2">{auditResult.issues.map((item) => <li key={item.id} className="rounded-2xl border border-slate-100 bg-slate-50 p-3 text-sm font-semibold text-slate-700"><Badge tone={item.severity === "warning" ? "amber" : "red"}>{item.severity}</Badge><span className="ml-2 font-black text-slate-950">{item.category}</span> · {item.clientName} · {item.sourceEntityId} · {item.reason}</li>)}</ul>}</div>}
      <div className="mt-5 flex flex-col gap-3 rounded-3xl border border-amber-100 bg-white p-5 xl:flex-row xl:items-center xl:justify-between"><p className="text-sm font-semibold leading-6 text-slate-700">La carga solo se habilita tras auditoría vigente, sin defectos bloqueantes y aprobación explícita. {hasActiveDemoSession ? "La sesión demo está activa." : "Inicia una sesión demo para generar."}</p><button disabled={!canInject} onClick={onInject} className="rounded-2xl bg-slate-950 px-6 py-4 text-base font-black text-white disabled:cursor-not-allowed disabled:bg-slate-300 disabled:text-slate-600"><UploadCloud size={18} className="mr-2 inline" />Cargar Empresa Demo simulada</button></div>
    </div>
    <div className="mt-5 rounded-3xl border border-emerald-100 bg-emerald-50 p-5"><div className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Estado consolidado de la corrida</div><h4 className="mt-2 text-xl font-black text-slate-950">Resumen de Datos Demo Cargados</h4><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Empresa demo" value={demoContext?.prospectCompanyName || "Pendiente"} /><Summary label="Proyecto" value={demoContext?.projectName || "Proyecto de Empresa Demo"} /><Summary label="Fecha / última actualización" value={demoContext?.injectedAt || "Pendiente"} /><Summary label="Estado demo" value={simulatedDataInjected ? "Cargado localmente" : approved ? "Aprobado, pendiente de carga" : "Pendiente"} /><Summary label="Persistencia" value="No persistido" /></div><div className="mt-5 grid grid-cols-5 overflow-hidden rounded-3xl border border-slate-200 bg-white text-sm font-black text-slate-950"><div className="bg-slate-100 p-4">{counts.reservations}</div><div className="bg-slate-100 p-4">{counts.vapiLogs}</div><div className="bg-slate-100 p-4">{counts.sellerReports}</div><div className="bg-slate-100 p-4">{counts.messages}</div><div className="bg-slate-100 p-4">{total}</div></div></div>
  </section>;
}
